feat: converted code to typescript
feedzai/AutoVizuA11y pull request #25
Opened 2024-06-26 13:51 UTC by DiogoRDuarte

## Because
- The current implementation does not make usage of Typescript, something that can hurt the development experience.
- These changes were previously suggested in another PR (now closed). Given its magnitude, it was decided to break it into smaller, more manageable, ones. Kudos to @JoaoTMDias ✌️

## This Commit

### Refactor
- Converts the codebase to typescript (except the JSX components which were left as plain JSX without any type inferrence).

2024-06-26 14:38 UTC, JoaoTMDias requested changes
Overall looks ok, what I feel it is needed is better jsdoc docs for all functions in the project. For open-source projects this is essential to read and understand code.

There's a vscode extension called "Document This" that helps with most of the properties necessary with jsdoc. But functions need short and concise descriptions.

2024-06-27 10:15 UTC, DiogoRDuarte commented
@JoaoTMDias Documentation added!

2024-06-27 10:41 UTC, JoaoTMDias approved these changes
Well done 👏

2024-06-27 13:28 UTC, ritacosta0 commented on src/AutoVizuA11y.tsx
> + * AutoVizuA11y component, that adds screen-reader accessibility to wrapped charts.
Please remove the comma.

2024-06-27 13:28 UTC, ritacosta0 commented on src/AutoVizuA11y.tsx
> + * 	selectorType, - HTML type or  classname of the data elements in the DOM;
Extra space between "or" and "classname"

2024-06-27 13:28 UTC, ritacosta0 commented on src/ShortcutGuide.tsx
> + * Component that renders the list (also visual) of all AutoVizuA11y shortcuts.
Does the "also visual" matter?

2024-06-27 13:28 UTC, ritacosta0 commented on src/components/descriptions/Descriptions.ts
> + * Handles the longer and shorter description change when Alt+B or Alt+S are pressed, respectively.
The alt+B and alt+S command is not for MacOS. Can you add the "option" detail here and everywhere you mention shortcuts in the documentation?

2024-06-27 13:28 UTC, ritacosta0 commented on src/components/navigation/LevelNavigation.ts
> + * Changes navigation based on key press.
What do we mean by "changes navigation" here?

2024-06-27 13:28 UTC, ritacosta0 commented on src/components/navigation/LevelNavigation.ts
> + * Shows the ShortcutGuide and gives it keyboard focus.
I suggest using the word "display" here

2024-06-27 13:28 UTC, ritacosta0 commented on src/components/navigation/LevelNavigation.ts
> + * Enables navigation on another data series.
It's more something like "Enables navigation between data series", no?

2024-06-27 13:28 UTC, ritacosta0 commented on src/components/shortcuts/OverallComparer.ts
> + * Produces a message based on corner cases and calls comparer otherwise.
What exactly do you mean about the "message based on corner cases"? Is that the focus of the function or is this secondary?

2024-06-27 13:28 UTC, ritacosta0 commented on src/components/shortcuts/Skip.ts
> + * Enables one to jump to the end/beginning of a chart.
Just for the phrasing to be more aligned with the others, I suggest writing something like "Enables the navigation to the end/beginning of a chart"

2024-06-27 13:28 UTC, ritacosta0 commented on src/utils/maths.ts
> + * Calculates the median value of a number array.
a number array -> an array of numbers

2024-06-27 13:28 UTC, ritacosta0 commented on src/utils/maths.ts
> + * Determines the ordinal version of a number.
Maybe something like "Transforms number to ordinal". Wdyt?

2024-06-27 13:56 UTC, DiogoRDuarte commented on src/ShortcutGuide.tsx
> + * Component that renders the list (also visual) of all AutoVizuA11y shortcuts.
I agree it can be cut

2024-06-27 14:41 UTC, merged